# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 568)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(900, 568))
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        self.treeView.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(False)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(160, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.countryLabel = QtWidgets.QLabel(self.groupBox)
        self.countryLabel.setObjectName("countryLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.countryLabel)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(160, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.dateLabel = QtWidgets.QLabel(self.groupBox)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setMinimumSize(QtCore.QSize(169, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setEnabled(True)
        self.dateEdit.setMinimumSize(QtCore.QSize(169, 30))
        self.dateEdit.setMouseTracking(True)
        self.dateEdit.setAutoFillBackground(True)
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit.setWrapping(True)
        self.dateEdit.setFrame(True)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setSpecialValueText("")
        self.dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit.setKeyboardTracking(True)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 11, 23), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dateEdit.setMinimumDate(QtCore.QDate(2019, 9, 30))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setDate(QtCore.QDate(2020, 11, 23))
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.testsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.testsLabel.setObjectName("testsLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.testsLabel)
        self.testSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.testSpinBox.setMinimumSize(QtCore.QSize(266, 30))
        self.testSpinBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.testSpinBox.setWrapping(False)
        self.testSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.testSpinBox.setAccelerated(True)
        self.testSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.testSpinBox.setProperty("showGroupSeparator", True)
        self.testSpinBox.setMaximum(999999999)
        self.testSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.testSpinBox.setObjectName("testSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.testSpinBox)
        self.casesLabel = QtWidgets.QLabel(self.groupBox_2)
        self.casesLabel.setObjectName("casesLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.casesLabel)
        self.deathsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.deathsLabel.setObjectName("deathsLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.deathsLabel)
        self.casesSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.casesSpinBox.setMinimumSize(QtCore.QSize(266, 30))
        self.casesSpinBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.casesSpinBox.setWrapping(False)
        self.casesSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.casesSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.casesSpinBox.setAccelerated(True)
        self.casesSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.casesSpinBox.setProperty("showGroupSeparator", True)
        self.casesSpinBox.setMaximum(999999999)
        self.casesSpinBox.setObjectName("casesSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.casesSpinBox)
        self.deathsSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.deathsSpinBox.setMinimumSize(QtCore.QSize(266, 30))
        self.deathsSpinBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.deathsSpinBox.setWrapping(False)
        self.deathsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deathsSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.deathsSpinBox.setAccelerated(True)
        self.deathsSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.deathsSpinBox.setProperty("showGroupSeparator", True)
        self.deathsSpinBox.setMaximum(999999999)
        self.deathsSpinBox.setObjectName("deathsSpinBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.deathsSpinBox)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setMinimumSize(QtCore.QSize(266, 30))
        self.spinBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setMinimumSize(QtCore.QSize(266, 30))
        self.spinBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.spinBox_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_3.setMinimumSize(QtCore.QSize(266, 30))
        self.spinBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.spinBox_3)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.btnHLayout = QtWidgets.QHBoxLayout()
        self.btnHLayout.setObjectName("btnHLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnHLayout.addItem(spacerItem)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setMinimumSize(QtCore.QSize(0, 40))
        self.removeButton.setObjectName("removeButton")
        self.btnHLayout.addWidget(self.removeButton)
        self.gridLayout_2.addLayout(self.btnHLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menuDownload = QtWidgets.QMenu(self.menu_edit)
        self.menuDownload.setObjectName("menuDownload")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.closeAction = QtWidgets.QAction(MainWindow)
        self.closeAction.setObjectName("closeAction")
        self.actionSaveChanges = QtWidgets.QAction(MainWindow)
        self.actionSaveChanges.setObjectName("actionSaveChanges")
        self.actionSaveCSV = QtWidgets.QAction(MainWindow)
        self.actionSaveCSV.setObjectName("actionSaveCSV")
        self.actionSaveJson = QtWidgets.QAction(MainWindow)
        self.actionSaveJson.setObjectName("actionSaveJson")
        self.menuDownload.addAction(self.actionSaveCSV)
        self.menuDownload.addAction(self.actionSaveJson)
        self.menu_edit.addSeparator()
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.menuDownload.menuAction())
        self.menu_edit.addAction(self.actionSaveChanges)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.closeAction)
        self.menubar.addAction(self.menu_edit.menuAction())
        self.countryLabel.setBuddy(self.comboBox)
        self.dateLabel.setBuddy(self.comboBox_2)
        self.testsLabel.setBuddy(self.testSpinBox)
        self.casesLabel.setBuddy(self.casesSpinBox)
        self.deathsLabel.setBuddy(self.deathsSpinBox)
        self.label.setBuddy(self.spinBox)
        self.label_2.setBuddy(self.spinBox_2)
        self.label_3.setBuddy(self.spinBox_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BiblioApp"))
        self.groupBox.setTitle(_translate("MainWindow", "Query"))
        self.countryLabel.setText(_translate("MainWindow", "Cou&ntry"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select a country"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select a date"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Today"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Yesterday"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "An other day"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Daily Report"))
        self.testsLabel.setText(_translate("MainWindow", "New &Tests"))
        self.casesLabel.setText(_translate("MainWindow", "New &cases"))
        self.deathsLabel.setText(_translate("MainWindow", "New &Deaths"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Cumulative Report"))
        self.label.setText(_translate("MainWindow", "Total Tests"))
        self.label_2.setText(_translate("MainWindow", "Total Cases"))
        self.label_3.setText(_translate("MainWindow", "Total Deaths"))
        self.removeButton.setText(_translate("MainWindow", "&Refresh"))
        self.menu_edit.setTitle(_translate("MainWindow", "Edit"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download all entries"))
        self.openAction.setText(_translate("MainWindow", "&Open"))
        self.openAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveAction.setText(_translate("MainWindow", "&Save"))
        self.saveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.closeAction.setText(_translate("MainWindow", "&Close"))
        self.closeAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSaveChanges.setText(_translate("MainWindow", "&Save changes"))
        self.actionSaveCSV.setText(_translate("MainWindow", "To CSV format"))
        self.actionSaveJson.setText(_translate("MainWindow", "To Json Format"))
